### ISSUE TITLE
does anyone test it on large website?

### ISSUE THREAD

**Issue by boynet** [adibalcan/record#5]
i am afraid that all that images writes gonna eat my hd.

**Comment by boynet** [comment]
just checked it for 1-2 minutes, the canvas2html screenshot make the website very slow :/ I think its better to save the html or something, and mimic the user behaviour on the html page(clicks scrolls etc)

**Comment by adibalcan** [comment]
Is just an experiment for testing this mode of recording

**Comment by moeiscool** [comment]
smartlook.com uses this

**Comment by adibalcan** [comment]
Thank you, Moe. 
I will close this issue.
